name: Create or Update Pull Request
description: "A GitHub Action to create or update a pull request based on local changes"
branding:
  icon: "git-pull-request"
  color: purple
inputs:
  title:
    description: "Pull Request title"
    required: true
    default: "Update from 'Create or Update Request' action"
  body:
    description: "Pull Request body"
    required: true
    default: |
      This pull request has been created by the ["Create or Update Pull Request" action](https://github.com/gr2m/create-or-update-pull-request-action#readme).

      You can set a custom pull request title, body, branch and commit messages, see [Usage](https://github.com/gr2m/create-or-update-pull-request-action#usage).
  branch:
    description: "Branch name"
    required: true
    default: create-or-update-pull-request-action
  author:
    description: Commit author name & email address. Must be in the form "Name <email@domain.com>"
    required: true
    default: "Create or Update Pull Request Action <create-or-update-pull-request@users.noreply.github.com>"
  commit-message:
    description: Commit message for all uncommited changes.
    required: true
    default: Update from 'Create or Update Request' action
  path-to-cd-to:
    description: Commit changes in another repository by providing a path to cd to (using Node's process.chdir function) before git operations.
    required: false
  labels:
    description: Comma separated list of labels to apply to the pull request
    required: false
  assignees:
    description: Comma separated list of assignees to apply to the pull request
    required: false
  repository:
    description: Repository name in the format owner/repo. Defaults to current repository if not given. Use with path-to-cd-to.
    required: false
  reviewers:
    description: Comma separated list of reviewers to apply to the pull request
    required: false
  team_reviewers:
    description: Comma separated list of team reviewers to apply to the pull request
    required: false
  auto-merge:
    description: "Enable auto merge for pull request. Requires auto merging to be enabled in repository settings"
    required: false
  update-pull-request-title-and-body:
    description: "Set to true if you want the title and body to be updated for an existing pull request"
    default: "false"
    required: false

outputs:
  pull-request-number:
    description: "Number of the created/updated pull request"
  result:
    description: "'updated', 'created', 'unchanged' based if the PR was created, updated or nothing happened"

runs:
  using: "node16"
  main: "dist/index.js"
